apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egov-maintenance-rb
  namespace: egov
subjects:
  - kind: ServiceAccount
    name: egov-maintenance-sa
    namespace: egov
roleRef:
  kind: Role
  name: egov-maintenance-role
  apiGroup: rbac.authorization.k8s.io
